include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - component: gitlab.onelitefeather.dev/dungeon/ci-components/gradle-publish@0.1.0
variables:
  SECURE_ANALYZERS_PREFIX: "${HTL_NEXUS_PROXY}/security-products"
  GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.10.0-jdk21"


test:
  script:
    - gradle jacocoTestReport
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/test/jacocoTestReport.xml
      junit: build/test-results/test/**/TEST-*.xml
